services:
  hankyung-bot:
    build: .
    image: hankyung-consensus-bot:latest
    container_name: hankyung-consensus-bot
    user: "1001:1001"
    restart: always
    env_file: .env
    volumes:
      - ~/sqlite3:/app/db
      - ~/log:/app/log
